# Generated by Django 4.0.1 on 2022-02-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_title_manga_title_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='title_text',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
