# Generated by Django 4.0.1 on 2022-02-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_rename_russiam_name_title_russian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='manga',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='manga.manga'),
        ),
    ]
