# Generated by Django 4.0.1 on 2022-02-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_magazine_manga_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
