# Generated by Django 4.0.1 on 2022-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_alter_manga_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='volumes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
