# Generated by Django 4.0.1 on 2022-02-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
        ('manga', '0014_alter_manga_chapters_alter_manga_volumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='anime',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='anime.anime'),
        ),
    ]
