# Generated by Django 4.0.1 on 2022-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_remove_title_anime_remove_title_manga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
