# Generated by Django 4.0.1 on 2022-02-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_description'),
        ('manga', '0017_alter_title_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='title',
            name='object_id',
        ),
        migrations.AddField(
            model_name='title',
            name='anime',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='title',
            name='manga',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='manga.manga'),
        ),
    ]
