# Generated by Django 4.0.1 on 2022-02-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0018_remove_title_content_type_remove_title_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='title',
            name='manga',
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='manga.title'),
        ),
    ]
