# Generated by Django 4.0.1 on 2022-02-28 10:48

from django.db import migrations, models
import manga.models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_remove_title_anime_remove_title_manga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(blank=True, upload_to=manga.models.image_path),
        ),
    ]
