# Generated by Django 4.0.1 on 2022-01-12 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('genre', '0001_initial'),
        ('type', '0001_initial'),
        ('demographic', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('alt_name', models.CharField(blank=True, max_length=1000)),
                ('premiered', models.DateField(blank=True)),
                ('episodes', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='item_pic/')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_type', to='contenttypes.contenttype')),
                ('demographic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_demo', to='demographic.demographic')),
                ('genres', models.ManyToManyField(blank=True, related_name='anime_genres', to='genre.Genre')),
                ('studio', models.ManyToManyField(blank=True, related_name='anime_studio', to='studio.Studio')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_type', to='type.type')),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
