# Generated by Django 4.0.1 on 2022-01-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'manga'), ('model', 'Manga')), models.Q(('app_label', 'anime'), ('model', 'Anime')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_type', to='contenttypes.contenttype'),
        ),
    ]
