# Generated by Django 4.0.1 on 2022-03-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_related_post_related_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anime',
        ),
    ]
