# Generated by Django 4.0.1 on 2022-08-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
