# Generated by Django 4.0.1 on 2022-05-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_related_anime_alter_related_manga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_to',
        ),
    ]
