# Generated by Django 4.0.1 on 2022-08-17 09:36

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.main_path),
        ),
    ]
