# Generated by Django 4.0.1 on 2022-05-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_related_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Related',
        ),
    ]
