# Generated by Django 4.0.1 on 2022-03-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_content_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='content',
        ),
    ]
