# Generated by Django 4.0.1 on 2022-03-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_alter_content_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='text',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.AddField(
            model_name='file',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='post.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='post.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='post.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='post.post'),
            preserve_default=False,
        ),
    ]
