# Generated by Django 4.0.1 on 2022-03-04 13:46

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_remove_file_owner_remove_image_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.FileField(default=1, upload_to=post.models.main_path),
            preserve_default=False,
        ),
    ]
