# Generated by Django 4.0.1 on 2022-03-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_alter_image_file_alter_post_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
