# Generated by Django 4.0.1 on 2022-03-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_remove_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='content',
        ),
    ]
