# Generated by Django 4.0.1 on 2022-03-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_rename_file_file_content_rename_file_image_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='content',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='url',
        ),
    ]
