# Generated by Django 4.0.1 on 2022-03-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_alter_post_related_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='prev',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
