# Generated by Django 4.0.1 on 2022-03-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_remove_content_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='prev',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
