# Generated by Django 4.0.1 on 2022-03-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_content_prev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='prev',
        ),
    ]
