# Generated by Django 4.0.1 on 2022-03-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_options'),
        ('manga', '0020_alter_manga_image'),
        ('post', '0034_alter_post_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.related'),
        ),
        migrations.AlterField(
            model_name='related',
            name='anime',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='related',
            name='manga',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='manga.manga'),
        ),
    ]
