# Generated by Django 4.0.1 on 2022-04-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedItem',
        ),
    ]
