# Generated by Django 4.0.1 on 2022-05-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationreverse',
            name='adaptation',
        ),
        migrations.RemoveField(
            model_name='adaptationreverse',
            name='based_on',
        ),
        migrations.RemoveField(
            model_name='sequelprequelanime',
            name='prequel',
        ),
        migrations.RemoveField(
            model_name='sequelprequelanime',
            name='sequel',
        ),
        migrations.RemoveField(
            model_name='sequelprequelmanga',
            name='prequel',
        ),
        migrations.RemoveField(
            model_name='sequelprequelmanga',
            name='sequel',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.DeleteModel(
            name='Adaptation',
        ),
        migrations.DeleteModel(
            name='AdaptationReverse',
        ),
        migrations.DeleteModel(
            name='SequelPrequelAnime',
        ),
        migrations.DeleteModel(
            name='SequelPrequelManga',
        ),
    ]
