# Generated by Django 4.0.1 on 2022-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='author',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='source',
        ),
    ]
