# Generated by Django 4.0.1 on 2022-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_remove_adaptationreverse_adaptation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='adaptation_anime',
            field=models.ManyToManyField(blank=True, related_name='based_on', to='titles.Anime'),
        ),
        migrations.AddField(
            model_name='manga',
            name='prequel',
            field=models.ManyToManyField(blank=True, related_name='sequel', to='titles.Manga'),
        ),
    ]
