# Generated by Django 4.0.1 on 2022-05-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_delete_relateditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationReverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='based_on', to='titles.manga')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation', to='titles.anime')),
            ],
        ),
    ]
