# Generated by Django 4.0.1 on 2022-04-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_remove_anime_author_remove_anime_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='titles.anime')),
                ('manga', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='titles.manga')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation', models.ManyToManyField(blank=True, related_name='adaptation', to='titles.RelatedItem')),
                ('based_on', models.ManyToManyField(blank=True, related_name='based_on', to='titles.RelatedItem')),
                ('prequel', models.ManyToManyField(blank=True, related_name='prequel', to='titles.RelatedItem')),
                ('sequel', models.ManyToManyField(blank=True, related_name='sequel', to='titles.RelatedItem')),
                ('spin_off', models.ManyToManyField(blank=True, related_name='spin_off', to='titles.RelatedItem')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='related_titles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='titles.relatedtitles'),
        ),
        migrations.AddField(
            model_name='manga',
            name='related_titles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='titles.relatedtitles'),
        ),
    ]
