# Generated by Django 4.0.1 on 2022-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_manga_adaptation_anime_manga_prequel'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='adaptation_manga',
            field=models.ManyToManyField(blank=True, related_name='based_on', to='titles.Manga'),
        ),
        migrations.AddField(
            model_name='anime',
            name='prequel',
            field=models.ManyToManyField(blank=True, related_name='sequel', to='titles.Anime'),
        ),
    ]
