# Generated by Django 4.0.1 on 2022-04-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_relateditem_relatedtitles_anime_related_titles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='related_titles',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='related_titles',
        ),
        migrations.DeleteModel(
            name='RelatedTitles',
        ),
    ]
