# Generated by Django 4.0.1 on 2022-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_remove_anime_adaptation_manga_remove_anime_prequel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ('title',)},
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['id'], name='titles_anim_id_54c1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['id'], name='titles_mang_id_27add6_idx'),
        ),
    ]
