# Generated by Django 4.0.1 on 2022-05-30 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_alter_anime_options_alter_manga_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='titles.Genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='titles.image'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='titles.Theme'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.ForeignKey(default='No title yet', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s', to='titles.title'),
        ),
    ]
