# Generated by Django 4.0.1 on 2022-04-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_sequelprequelmanga_sequelprequel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SequelPrequel',
            new_name='SequelPrequelAnime',
        ),
    ]
