# Generated by Django 4.0.1 on 2022-05-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_remove_manga_publisher_alter_manga_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='publisher',
            field=models.ManyToManyField(blank=True, related_name='manga', to='titles.Publisher'),
        ),
    ]
