# Generated by Django 4.0.1 on 2022-05-30 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_manga_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='titles.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='titles.image'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='premiere',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='titles.Theme'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.ForeignKey(default='No title yet', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s', to='titles.title'),
        ),
    ]
