# Generated by Django 4.0.1 on 2022-05-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_anime_related_posts_manga_related_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='related_posts',
            new_name='related_post',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='related_posts',
            new_name='related_post',
        ),
    ]
