# Generated by Django 4.0.1 on 2022-06-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_rename_related_posts_anime_related_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='title_language/')),
            ],
        ),
        migrations.RemoveField(
            model_name='title',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='russian_name',
        ),
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, upload_to='magazines/'),
        ),
        migrations.AddField(
            model_name='title',
            name='title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='titles.titlelanguage'),
        ),
    ]
