# Generated by Django 4.0.1 on 2022-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default={'dark_mode': False,}),
        ),
    ]
