# Generated by Django 4.0.1 on 2022-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default={'dark_mode': False}),
        ),
    ]
