# Generated by Django 4.0.1 on 2022-05-25 11:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=accounts.models.preferences_dict),
        ),
    ]
