# Generated by Django 4.0.1 on 2022-01-10 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('alt_name', models.CharField(max_length=1000)),
                ('studio', models.CharField(max_length=100)),
                ('premiered', models.DateTimeField()),
                ('episodes', models.DecimalField(decimal_places=0, max_digits=5)),
                ('genres', models.CharField(max_length=100)),
                ('Demographic', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
