# Generated by Django 4.0.1 on 2022-02-15 14:36

import anime.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manga', '0014_alter_manga_chapters_alter_manga_volumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='', max_length=250)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='manga/')),
                ('slug', models.SlugField(default='', max_length=250)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('premiere', models.DateField(blank=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=anime.models.image_path)),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='manga.author')),
                ('demographic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='manga.demographic')),
                ('genres', models.ManyToManyField(blank=True, related_name='anime', to='manga.Genre')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='manga.manga')),
                ('studio', models.ManyToManyField(blank=True, related_name='anime', to='anime.Studio')),
                ('themes', models.ManyToManyField(blank=True, related_name='anime', to='manga.Theme')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='anime.animetype')),
            ],
        ),
    ]
