# Generated by Django 4.0.1 on 2022-02-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='demographic',
        ),
    ]
