# Generated by Django 4.0.1 on 2022-01-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_studio_alter_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_studio', to='anime.studio'),
        ),
    ]
