# Generated by Django 4.0.1 on 2022-02-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0015_title_anime'),
        ('anime', '0002_remove_anime_demographic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='manga.author'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='anime', to='manga.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='premiere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, null=True, related_name='anime', to='anime.Studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, related_name='anime', to='manga.Theme'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='anime.animetype'),
        ),
    ]
