# Generated by Django 4.0.1 on 2022-01-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0002_delete_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.CharField(max_length=500)),
                ('slug', models.SlugField(default='', max_length=250)),
            ],
        ),
    ]
