# Generated by Django 4.0.1 on 2022-01-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_studio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
