# Generated by Django 4.0.1 on 2022-01-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
