# Generated by Django 4.0.1 on 2022-02-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_remove_title_anime_remove_title_manga_and_more'),
        ('anime', '0004_alter_anime_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='manga.title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime', to='manga.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, related_name='anime', to='anime.Studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='anime', to='manga.Theme'),
        ),
    ]
