# Generated by Django 4.0.1 on 2022-01-10 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0004_delete_anime_delete_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-studio',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-type',),
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('alt_name', models.CharField(max_length=1000)),
                ('premiered', models.DateTimeField()),
                ('episodes', models.DecimalField(decimal_places=0, max_digits=5)),
                ('genres', models.CharField(max_length=100)),
                ('Demographic', models.CharField(max_length=100)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_studio', to='anime.studio')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_type', to='anime.type')),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
