# Generated by Django 4.0.1 on 2022-01-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='Demographic',
            new_name='demographic',
        ),
    ]
