# Generated by Django 4.0.1 on 2022-03-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_title_alter_anime_genres_alter_anime_studio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('-title',)},
        ),
    ]
