# Generated by Django 4.0.1 on 2022-01-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_rename_demographic_anime_demographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, upload_to='anime_pic/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, upload_to='studio_pic/'),
        ),
    ]
