# Generated by Django 4.0.1 on 2022-01-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_anime_episodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-demographic',),
            },
        ),
        migrations.AlterField(
            model_name='anime',
            name='demographic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_demo', to='anime.demographic'),
        ),
    ]
