# Generated by Django 4.0.1 on 2022-01-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_demographic_alter_anime_demographic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-genres',),
            },
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_genres', to='anime.genre'),
        ),
    ]
