# Generated by Django 4.0.1 on 2022-01-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_genre_alter_anime_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genres',
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime_genres', to='anime.Genre'),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(related_name='anime_studio', to='anime.Studio'),
        ),
    ]
