# Generated by Django 4.0.1 on 2022-01-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_remove_anime_genres_anime_genres_remove_anime_studio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='alt_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='anime',
            name='demographic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_demo', to='anime.demographic'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime_genres', to='anime.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='premiered',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, related_name='anime_studio', to='anime.Studio'),
        ),
    ]
