# Generated by Django 4.0.1 on 2022-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_anime_alt_name_alter_anime_demographic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='demographic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
