# Generated by Django 4.0.1 on 2022-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_alter_demographic_demographic_alter_genre_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='demographic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
