# Generated by Django 4.0.1 on 2022-01-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_alter_demographic_demographic_alter_genre_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='demographic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_demo', to='anime.demographic'),
        ),
    ]
