# Generated by Django 4.0.1 on 2022-01-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_alter_anime_demographic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='anime_genres', to='anime.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, null=True, related_name='anime_studio', to='anime.Studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_type', to='anime.type'),
        ),
    ]
