# Generated by Django 4.0.1 on 2022-01-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_alter_anime_genres_alter_anime_studio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime_genres', to='anime.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, related_name='anime_studio', to='anime.Studio'),
        ),
    ]
