# Generated by Django 4.0.1 on 2022-01-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_demographic_slug_genre_slug_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
